--- #YAML:1.0
name:                Chart-Plot-Canvas
version:             0.03
abstract:            Plot two dimensional data in an Tk Canvas
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Chart::Plot:                   0.11
    Tk:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Francois PERRAD (francois.perrad@gadz.org)
